default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: txhims

test:
  <<: *default
  database: txmanager_test

production:
  <<: *default
  database: txmanager_production
  username: txmanager
  password: <%= ENV['TXMANAGER_DATABASE_PASSWORD'] %>
